# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/search.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/search.proto\x12\x11\x64istributedsearch\"-\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\"p\n\x0cSearchResult\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x01\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t\x12\x0f\n\x07snippet\x18\x05 \x01(\t\x12\x0f\n\x07node_id\x18\x06 \x01(\t\"o\n\x0eSearchResponse\x12\x30\n\x07results\x18\x01 \x03(\x0b\x32\x1f.distributedsearch.SearchResult\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x1a\n\x12statistics_version\x18\x03 \x01(\t2^\n\rSearchService\x12M\n\x06Search\x12 .distributedsearch.SearchRequest\x1a!.distributedsearch.SearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHREQUEST']._serialized_start=41
  _globals['_SEARCHREQUEST']._serialized_end=86
  _globals['_SEARCHRESULT']._serialized_start=88
  _globals['_SEARCHRESULT']._serialized_end=200
  _globals['_SEARCHRESPONSE']._serialized_start=202
  _globals['_SEARCHRESPONSE']._serialized_end=313
  _globals['_SEARCHSERVICE']._serialized_start=315
  _globals['_SEARCHSERVICE']._serialized_end=409
# @@protoc_insertion_point(module_scope)
